### ISSUE TITLE
Consider supporting &mut self

### ISSUE THREAD

**Issue by junha1** [CodeChain-io/remote-trait-object#40]
The easiest approach is wrapping all service objects in `RwLock` and registering them on the server.
The proc-macro also need to choose `.read()` or `.write()` depending on the methods, in the `Dispatcher`
But it will be more complicated to support this in a zero-cost way, including change of the interface.
Here being zero-cost means that you shouldn't pay the cost of inevitably having `RwLock` even for the traits where all methods take `&self`.

**Comment by majecty** [comment]
@junha1 I think, having `RwLock` with overhead seems ok. IMO we are not forced to get maximum performance.

@junha1 @sgkim126 

I don't know what should be semantic of the `mut` keyword in remote-trait-object.
There are some points that need a discussion.

## Terms

**ServiceObject**: the server-side of remote-trait-object. When a program received a message from network, a service object's functions will be called.
**RemoteServiceObject**: the client-side of remote-trait-object. If a program uses `remote_service_object.foo()`, it will send a network packet to a server and wait until the server returns result.

## 1. What should be the remote service object's type?
  1.1 Arc<RwLock\<dyn Service>>
  1.2 Box\<dyn Service>

@junha1 I heard from you that we can't use Box<Service>. Sorry, I couldn't remember the reason. IMO for now, we can use Box<Service>. When we register the `Box<Service>` to port, we can change Box<Service> to Arc<Service>.

## 2. `mut` function and `non-mut` function can be called at the same time

We may enforce **a** remote service object not be able to call mut and non-mut function at the same time using `mut` semantic. However, multiple programs can send them at the same time. A program X can send `set(&mut self)` call and a program Y can send `read(&self)` at the same time. It's a bit different from Rust's `mut` behavior. Do you think it's acceptable behavior?

## 3. When a mut function and non-mut function is called in parallel, how the service object(server-side)'s functions should be called? 
  2.1 Run the mut function and non-mut function in parallel using multi-thread
  2.2. Run like RwLock: non-mut functions can be called parallel in multi-thread. If a mut function is called, other calls are blocked.
  2.3 Run like Mutex: Only one mut function or non-mut function can be called at a time.

If we choose 2.1, a service object writer needs to implement correct lock behavior. 
If we choose 2.2, it will act similarly to the Rust's mut semantic. However, I don't know the locking is a user's requirements or not.
If we choose 2.3, IMO 2.2 is always better than 2.3.

**Comment by junha1** [comment]
The reason we use `Arc` instead of `Box` is to support multiple registration of a single instnace.

**Comment by majecty** [comment]
We may make ServiceObject implement `Clone`. If we make the fields of ServiceObject with `Arc`, we can share the same ServiceObject by using `Clone`. However, I don't know it is easy to use without a real example.
